#!/usr/bin/env python3
"""
Render classified bookmarks CSV into Netscape bookmark HTML.

Input CSV columns (required):
  大类,小类,网站标题,备注说明,网址

Output:
  Netscape bookmark HTML file containing:
  - 大类 -> 小类 -> bookmarks

Notes:
- This script does not deduplicate; it assumes CSV is already deduped.
- HTML is generated with escaped attribute/title/description.
"""

from __future__ import annotations

import argparse
import csv
import html
import time
from collections import defaultdict
from pathlib import Path
from typing import DefaultDict, Dict, List, Tuple


def esc_attr(s: str) -> str:
    # Escape for attribute value; quote=True escapes double quotes.
    return html.escape(s or "", quote=True)


def esc_text(s: str) -> str:
    # Escape for element text.
    return html.escape(s or "", quote=False)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="Classified CSV path")
    ap.add_argument("--output", required=True, help="HTML output path")
    ap.add_argument(
        "--personal-toolbar",
        action="store_true",
        help='Wrap big categories under a top folder with PERSONAL_TOOLBAR_FOLDER="true"',
    )
    ap.add_argument(
        "--epoch",
        type=int,
        default=int(time.time()),
        help="ADD_DATE and LAST_MODIFIED epoch used in HTML",
    )
    args = ap.parse_args()

    inp = Path(args.input)
    outp = Path(args.output)

    rows: List[Dict[str, str]] = []
    with inp.open("r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            rows.append(row)

    # Group by big/small keeping original order per (big, small)
    grouped: DefaultDict[str, DefaultDict[str, List[Dict[str, str]]]] = defaultdict(lambda: defaultdict(list))
    for row in rows:
        big = (row.get("大类") or "").strip() or "工具"
        small = (row.get("小类") or "").strip() or "通用资源"
        grouped[big][small].append(row)

    epoch = int(args.epoch)

    dl_prefix = '<DL><p>'
    dl_suffix = "</DL><p>"

    parts: List[str] = []
    parts.append("<!DOCTYPE NETSCAPE-Bookmark-file-1>")
    parts.append("<!-- Auto-generated by bookmark-organize-b -->")
    parts.append('<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">')
    parts.append("<TITLE>Bookmarks</TITLE>")
    parts.append("<H1>Bookmarks</H1>")

    parts.append(dl_prefix)

    if args.personal_toolbar:
        # Provide a top container similar to Edge bookmark bar structure.
        parts.append(
            f'    <DT><H3 ADD_DATE="{epoch}" LAST_MODIFIED="{epoch}" PERSONAL_TOOLBAR_FOLDER="true">收藏夹栏</H3>'
        )
        parts.append("    <DL><p>")

        for big in grouped.keys():
            parts.append(f'        <DT><H3 ADD_DATE="{epoch}" LAST_MODIFIED="{epoch}">{esc_text(big)}</H3>')
            parts.append("        <DL><p>")
            for small in grouped[big].keys():
                parts.append(
                    f'            <DT><H3 ADD_DATE="{epoch}" LAST_MODIFIED="{epoch}">{esc_text(small)}</H3>'
                )
                parts.append("            <DL><p>")
                for row in grouped[big][small]:
                    href = (row.get("网址") or "").strip()
                    title = row.get("网站标题") or ""
                    desc = row.get("备注说明") or ""
                    desc_attr = f' DESCRIPTION="{esc_attr(desc)}"' if desc else ""
                    parts.append(
                        f'                <DT><A HREF="{esc_attr(href)}" ADD_DATE="{epoch}" LAST_MODIFIED="{epoch}"{desc_attr}>{esc_text(title)}</A>'
                    )
                parts.append("            </DL><p>")
            parts.append("        </DL><p>")

        parts.append("    </DL><p>")
    else:
        # Default: big categories at root.
        for big in grouped.keys():
            parts.append(
                f'    <DT><H3 ADD_DATE="{epoch}" LAST_MODIFIED="{epoch}">{esc_text(big)}</H3>'
            )
            parts.append("    <DL><p>")
            for small in grouped[big].keys():
                parts.append(
                    f'        <DT><H3 ADD_DATE="{epoch}" LAST_MODIFIED="{epoch}">{esc_text(small)}</H3>'
                )
                parts.append("        <DL><p>")
                for row in grouped[big][small]:
                    href = (row.get("网址") or "").strip()
                    title = row.get("网站标题") or ""
                    desc = row.get("备注说明") or ""
                    desc_attr = f' DESCRIPTION="{esc_attr(desc)}"' if desc else ""
                    parts.append(
                        f'            <DT><A HREF="{esc_attr(href)}" ADD_DATE="{epoch}" LAST_MODIFIED="{epoch}"{desc_attr}>{esc_text(title)}</A>'
                    )
                parts.append("        </DL><p>")
            parts.append("    </DL><p>")

    parts.append(dl_suffix)

    # Close HTML
    outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"rendered: output={outp} groups={len(grouped)}")


if __name__ == "__main__":
    main()

